# Generated by Django 5.0 on 2023-12-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='last_фамилия',
            new_name='last_name',
        ),
    ]
