# Generated by Django 5.0 on 2023-12-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0002_rename_last_фамилия_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='addres',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='office',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wherhouse',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='area',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.category'),
        ),
        migrations.CreateModel(
            name='Complimentary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('IdWarehouseMinus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_minus', to='studentdb.warehouse')),
                ('IdWarehousePlus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_plus', to='studentdb.warehouse')),
                ('IdComponents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.components')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalOfComponents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('IdWarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.warehouse')),
                ('IdComponents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.components')),
            ],
        ),
        migrations.CreateModel(
            name='MotionFromProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('IdEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.employee')),
                ('IdOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.office')),
                ('IdProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdb.product')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('IdWarehouseMinus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_minus', to='studentdb.warehouse')),
                ('IdWarehousePlus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_plus', to='studentdb.warehouse')),
            ],
        ),
    ]
