# Generated by Django 3.2.12 on 2023-12-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0003_category_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionfromproduct',
            name='IdComponents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentdb.components'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motionfromproduct',
            name='IdWarehouse',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='studentdb.warehouse'),
            preserve_default=False,
        ),
    ]
