# Generated by Django 3.2.12 on 2023-12-12 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0004_auto_20231212_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionfromproduct',
            name='IdComponents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentdb.components'),
        ),
        migrations.AlterField(
            model_name='motionfromproduct',
            name='IdWarehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentdb.warehouse'),
        ),
    ]
